package models

import "time"

type GroupReleasePolicy struct {
	OperationKind                  string
	RollbackOperationKind          string
	ScopePrefix                    string
	ScopeSuffix                    string
	RollbackScopeSuffix            string
	AuditAction                    string
	RollbackAuditAction            string
	SuccessResult                  string
	FailureResult                  string
	PendingState                   string
	RunningState                   string
	SucceededState                 string
	FailedState                    string
	JournalPendingState            string
	JournalCompleteState           string
	JournalFailedState             string
	FragmentSeparator              string
	IdempotencyWindow              time.Duration
	SystemGroupID                  string
	SystemGroupKind                string
	InvalidConfiguration           string
	MetadataPart                   string
	CaddyfilePart                  string
	ArtifactPart                   string
	MultipartContentType           string
	RequestLimitBytes              int64
	CompressedArtifactLimitBytes   int64
	UncompressedArtifactLimitBytes int64
	ArtifactEntryLimit             int
	CompressionRatioLimit          int64
	ArtifactPathByteLimit          int
	ArtifactPathDepthLimit         int
	ArtifactSuffix                 string
	MetadataContentType            string
	CaddyfileContentType           string
	ArtifactContentType            string
	ArtifactFileMode               uint32
	ArtifactDirectoryMode          uint32
	InvalidRequestCode             string
	RevisionConflictCode           string
	IdempotencyConflictCode        string
	CaddyAdaptFailedCode           string
	ArtifactInvalidCode            string
	ArtifactTooLargeCode           string
	ActivationFailedCode           string
	MetadataIdempotencyKeyField    string
	MetadataExpectedRevisionField  string
	ExpectedCurrentRevisionField   string
	RevisionIDPattern              string
}
